### ISSUE TITLE
Add Option to Adjust Hyperparams via Env Vars

### ISSUE THREAD

**Issue by Maxusmusti** [mlcommons/mlcube#270]
It would be nice for use in Kubernetes, OpenShift, and other cloud-based environments if the user had the option of setting hyperparameters via env vars rather than having to create and mount a ConfigMap for the yaml file, alter the image, or create a custom entrypoint script.

**Comment by kpouget** [comment]
Here is an example of how we can configure the execution, by specifying the hyperparameters as part of the Kubernetes Job/Pod environment specs:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: {job_name}
spec:
    spec:
      containers:
      - name: cnt
        env:
        - name: SSD_THRESHOLD
          value: "{settings_threshold}"
        - name: SSD_EPOCH
          value: "{settings_epoch}"
```
